@Reddit_MVP_backend_HostAddress = http://localhost:5019

GET {{Reddit_MVP_backend_HostAddress}}/weatherforecast/
Accept: application/json

### Register User
POST https://localhost:7117/api/auth/register
Content-Type: application/json

{
  "username": "amir",
  "email": "amir@test.com",
  "password": "Password123"
}

### Login with username
POST https://localhost:7117/api/auth/login
Content-Type: application/json

{
  "login": "amir",
  "password": "Password123"
}

### Login with email
POST https://localhost:7117/api/auth/login
Content-Type: application/json

{
  "login": "amir@test.com",
  "password": "Password123"
}

### Get Current User
GET https://localhost:7117/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImUxYzIxODBkLTNjOGItNDM0Yi1hODgzLTU1MWNkNDM1MTQxNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbWlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYW1pckB0ZXN0LmNvbSIsImV4cCI6MTc4NjIyMzI4MCwiaXNzIjoiUmVkZGl0TXZwQXBpIiwiYXVkIjoiUmVkZGl0TXZwQ2xpZW50In0.EeDGAMGjfFZkPxRrz9N35QhGuGLAv-kbps9mHOXnFS8

### Get Current User without token
GET https://localhost:7117/api/auth/me

### Login
POST https://localhost:7117/api/auth/login
Content-Type: application/json
{
  "login": "amir",
  "password": "Password123"
}

### Create Community
POST https://localhost:7117/api/communities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImUxYzIxODBkLTNjOGItNDM0Yi1hODgzLTU1MWNkNDM1MTQxNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbWlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYW1pckB0ZXN0LmNvbSIsImV4cCI6MTc4Njg0OTI0MCwiaXNzIjoiUmVkZGl0TXZwQXBpIiwiYXVkIjoiUmVkZGl0TXZwQ2xpZW50In0.D7aGPyQVjomFQTDxvJsqtSDsNb-ZzUyF5IuCCS8gwdY
{
  "name": "dotnet",
  "description": "A community for C#, ASP.NET Core, EF Core, and .Net developers.",
  "bannerImageUrl": null
}

### Get Communities
GET https://localhost:7117/api/communities

### Get Community by name
GET https://localhost:7117/api/communities/dotnet

### Join Community
POST https://localhost:7117/api/communities/1/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImUxYzIxODBkLTNjOGItNDM0Yi1hODgzLTU1MWNkNDM1MTQxNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbWlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYW1pckB0ZXN0LmNvbSIsImV4cCI6MTc4Njg0OTI0MCwiaXNzIjoiUmVkZGl0TXZwQXBpIiwiYXVkIjoiUmVkZGl0TXZwQ2xpZW50In0.D7aGPyQVjomFQTDxvJsqtSDsNb-ZzUyF5IuCCS8gwdY

### Leave Community
DELETE https://localhost:7117/api/communities/1/leave
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImUxYzIxODBkLTNjOGItNDM0Yi1hODgzLTU1MWNkNDM1MTQxNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbWlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYW1pckB0ZXN0LmNvbSIsImV4cCI6MTc4Njg0OTI0MCwiaXNzIjoiUmVkZGl0TXZwQXBpIiwiYXVkIjoiUmVkZGl0TXZwQ2xpZW50In0.D7aGPyQVjomFQTDxvJsqtSDsNb-ZzUyF5IuCCS8gwdY


### Create post
POST https://localhost:7117/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImUxYzIxODBkLTNjOGItNDM0Yi1hODgzLTU1MWNkNDM1MTQxNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbWlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYW1pckB0ZXN0LmNvbSIsImV4cCI6MTc4NzM1OTUxMiwiaXNzIjoiUmVkZGl0TXZwQXBpIiwiYXVkIjoiUmVkZGl0TXZwQ2xpZW50In0.3_MNz9Jd8GIQvZ9xqzFfK4MzPgFmJwurRJIdJUe0wYg

{
  "communityId": 1,
  "title": "First post in r/dotnet",
  "content": "This is the first real post created through the API.",
  "imageUrl": null
}

### Get all posts
GET https://localhost:7117/api/posts

### Get post by id
GET https://localhost:7117/api/posts/1

### Get community posts
GET https://localhost:7117/api/communities/dotnet/posts

### Update post
PUT https://localhost:7117/api/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImUxYzIxODBkLTNjOGItNDM0Yi1hODgzLTU1MWNkNDM1MTQxNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbWlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYW1pckB0ZXN0LmNvbSIsImV4cCI6MTc4NzM1OTUxMiwiaXNzIjoiUmVkZGl0TXZwQXBpIiwiYXVkIjoiUmVkZGl0TXZwQ2xpZW50In0.3_MNz9Jd8GIQvZ9xqzFfK4MzPgFmJwurRJIdJUe0wYg
{
  "title": "Updated first post",
  "content": "Updated content from the API.",
  "imageUrl": null
}

### Upvote post
POST https://localhost:7117/api/posts/1/vote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImUxYzIxODBkLTNjOGItNDM0Yi1hODgzLTU1MWNkNDM1MTQxNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbWlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYW1pckB0ZXN0LmNvbSIsImV4cCI6MTc4ODA3MDMxNywiaXNzIjoiUmVkZGl0TXZwQXBpIiwiYXVkIjoiUmVkZGl0TXZwQ2xpZW50In0.o52ZH05qEIym9LW37kyZvrWy8qEsBNxiHaNr9I1h6sk
{
  "value": 1
}

### Downvote post
POST https://localhost:7117/api/posts/1/vote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImUxYzIxODBkLTNjOGItNDM0Yi1hODgzLTU1MWNkNDM1MTQxNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbWlyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYW1pckB0ZXN0LmNvbSIsImV4cCI6MTc4ODA3MDMxNywiaXNzIjoiUmVkZGl0TXZwQXBpIiwiYXVkIjoiUmVkZGl0TXZwQ2xpZW50In0.o52ZH05qEIym9LW37kyZvrWy8qEsBNxiHaNr9I1h6sk
{
  "value": -1
}